version: "3.3"
services:
  db:
    image: mysql
    volumes:
     - db_data:/var/lib/mysql
    env_file:
      - ".env"
    restart: unless-stopped
  telegram_translator:
    restart: unless-stopped
    env_file:
      - ".env"
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.telegramtranslator.rule=Host(`ttranslate.duckdns.org`)"
      - "traefik.http.routers.telegramtranslator.entrypoints=websecure"
      - "traefik.http.routers.telegramtranslator.tls.certresolver=myhttpchallenge"
      - "traefik.http.services.telegramtranslator.loadbalancer.server.port=443"
    depends_on:
       - db
  traefik:
    image: traefik
    container_name: "traefik"
    restart: unless-stopped
    ports:
      - "9001:8080"
      - "443:443"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/letsencrypt:/letsencrypt"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myhttpchallenge.acme.email=${ADMIN_EMAIL}"
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
